CREATE TABLE Professores (
    ID_PROF INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    EMAIL VARCHAR(100),
    FONE VARCHAR(100)
);

CREATE TABLE Disciplinas (
    ID_DISCI INT PRIMARY KEY AUTO_INCREMENT,
    DISCIPLINA VARCHAR(60),
    CARGA_HORARIA INT,
    ID_PROF_FK INT,
    FOREIGN KEY (ID_PROF_FK) REFERENCES Professores(ID_PROF)
);

CREATE TABLE Alunos (
    ID_ALUNO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    EMAIL VARCHAR(100),
    FONE VARCHAR(10)
);

CREATE TABLE Notas (
    ID_NOTA INT PRIMARY KEY AUTO_INCREMENT,
    ID_DISC_FK INT,
    ID_ALUNO_FK INT,
    NOTA_FINAL DECIMAL(5,2),
    FALTAS INT,
    FOREIGN KEY (ID_DISC_FK) REFERENCES Disciplinas(ID_DISCI),
    FOREIGN KEY (ID_ALUNO_FK) REFERENCES Alunos(ID_ALUNO)
);